version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - lizhongyue248
  ignore:
  - dependency-name: github.com/go-playground/validator/v10
    versions:
    - 10.4.2
