- message: "$payload.pull_request.user.login"
  color: "purple"

- label: "Preview"
  message: "PR $prNumber"
  color: "blue"
  url: "https://pr-$prNumber.company.com"

- label: "PR Size"
  message: "Large"
  color: "red"
  when: "$additions >= 500"

- label: "PR Size"
  message: "Medium"
  color: "yellow"
  when: "$additions >= 200 && $additions < 500"

- label: "PR Size"
  message: "Normal"
  color: "green"
  when: "$additions < 200"
