style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/baishan-development-guizhou/golang-library
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - refactor
        - docs
    sort_by: Scope
  commit_groups:
    group_by: Type
    sort_by: Title
    title_maps:
      feat: ✨ Features
      fix: 🐛 Bug Fixes
      perf: ⚡️ Performance Improvements
      refactor: ♻️ Code Refactoring
      docs: 📝 Documents
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  issues:
    prefix:
      - #
  refs:
    actions:
      - Closes
      - Fixes
  notes:
    keywords:
      - BREAKING CHANGE